#!/bin/sh
set -e
# notice the / at end in order to load this module
PACKAGE='ee-first'
SEDCMD="s,require\s*[(]\s*'[.][.],require('$PACKAGE,g"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT INT TERM HUP

mkdir -p "$tmpdir/module-ee-first"
cp -r module-ee-first/test "$tmpdir/module-ee-first"
find module-ee-first/test/ -name '*.js' -print0 | \
    xargs -n1 -0 \
	  sh -c 'set -e; echo "TESTING: $3"; sed "$1" < "$3" > "$2/$3"' sedtape "$SEDCMD" "$tmpdir"
cd "$tmpdir/module-ee-first"
mocha -R spec --exit
