#!/bin/sh
set -e
# notice the / at end in order to load this module
PACKAGE='on-finished'
SEDCMD="s,require\s*[(]\s*'[.][.],require('$PACKAGE,g"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT INT TERM HUP

cp -r test $tmpdir
find test/ -name '*.js' -print0 | \
    xargs -n1 -0 \
	  sh -c 'set -e; echo "TESTING: $3"; sed "$1" < "$3" > "$2/$3"' sedtape "$SEDCMD" "$tmpdir"
cd "$tmpdir"
mocha -R spec --exit
